name: todo_app
description: A new Flutter project.

environment:
  sdk: ^3.9.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  sembast: ^3.7.1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true